apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-pages-site
  title: GitHub Pages Website
  description: Create a static HTML website and publish it via GitHub pages.

spec:
  owner: user:bmalouf-deloitte
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - website_name
      properties:
        website_name:
          title: Website name
          type: string
          description: This will be displayed prominantly on your website and in the title tag.
        website_pagerduty_escalation_policy_id:
          title: PagerDuty Escalation Policy ID
          type: string
          description: Find these at pagerduty.com/escalation_policies. It is the part of the URL after the hash.

    - title: Choose a Source Control Management tool to store your new website in.
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          website_name: ${{ parameters.website_name }}

    - id: publishToGitHub
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'A static HTML website. Just like the good old days.'
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public

    - id: readActivationPoints
      name: Read activation points
      action: http:backstage:request
      input:
        method: 'GET'
        path: /api/roadie-activation/activation-points

    - id: registerInPagerDuty
      name: Register in PagerDuty
      action: http:backstage:request
      input:
        method: 'POST'
        path: /api/proxy/pagerduty/services
        headers:
          content-type: 'application/json'
        body:
          service:
            name: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
            description: 'A static HTML website. Just like the good old days.'
            escalation_policy:
              id: ${{ parameters.website_pagerduty_escalation_policy_id }}
              type: escalation_policy_reference

    # - id: publishToWeb
    #   name: Publish to web
    #   action: http:backstage:request
    #   input:
    #     method: 'POST'
    #     path: /api/proxy/github-api/repos/${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}/${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}/pages
    #     headers:
    #       content-type: 'application/json'
    #     body:
    #       source:
    #         branch: main
    #         path: '/'

  output:
    remoteUrl: ${{ steps.publishToGitHub.output.remoteUrl }}
    activationPoints: ${{ steps.readActivationPoints.output.body }}
    activationPointsCode: ${{ steps.readActivationPoints.output.code }}
    # getResponse: ${{ steps.publishToWeb.output.body }}
    # getCode: ${{ steps.publishToWeb.output.code }}
    # getHeaders: ${{ steps.publishToWeb.output.headers }}
